package SP_helicopter1.soap;

import SP_helicopter1.output.*;
import SP_helicopter1.input.*;

import java.util.concurrent.Future;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-03-24T01:33:09.456+01:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0", name = "ServiceName_3PortType")
@XmlSeeAlso({ ObjectFactory.class })
public interface ServiceName3PortType {

	@WebMethod(operationName = "CapabilityName_3_2")
	@Oneway
	@RequestWrapper(localName = "CapabilityName_3_2", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0", className = "SP_helicopter1.soap.CapabilityName_3_2")
	public void capabilityName32(
			@WebParam(name = "arg0", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0") InputDataClassName_3_2 arg0);

	@WebMethod(operationName = "CapabilityName_3_1")
	@RequestWrapper(localName = "CapabilityName_3_1", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0", className = "SP_helicopter1.soap.CapabilityName_3_1")
	@ResponseWrapper(localName = "CapabilityName_3_1Response", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0", className = "SP_helicopter1.soap.CapabilityName_3_1Response")
	public Response<SP_helicopter1.soap.CapabilityName_3_1Response> capabilityName31Async(
			@WebParam(name = "arg0", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0") InputDataClassName_3_1 arg0);

	@WebMethod(operationName = "CapabilityName_3_1")
	@ResponseWrapper(localName = "CapabilityName_3_1Response", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0", className = "SP_helicopter1.soap.CapabilityName_3_1Response")
	@RequestWrapper(localName = "CapabilityName_3_1", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0", className = "SP_helicopter1.soap.CapabilityName_3_1")
	public Future<?> capabilityName31Async(
			@WebParam(name = "arg0", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0") InputDataClassName_3_1 arg0,
			@WebParam(name = "asyncHandler", targetNamespace = "") AsyncHandler<SP_helicopter1.soap.CapabilityName_3_1Response> asyncHandler);

	@WebMethod(operationName = "CapabilityName_3_1")
	@RequestWrapper(localName = "CapabilityName_3_1", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0", className = "SP_helicopter1.soap.CapabilityName_3_1")
	@ResponseWrapper(localName = "CapabilityName_3_1Response", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0", className = "SP_helicopter1.soap.CapabilityName_3_1Response")
	@WebResult(name = "return", targetNamespace = "")
	public OutputDataClassName_3_1 capabilityName31(
			@WebParam(name = "arg0", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0") InputDataClassName_3_1 arg0);
}
