package sp_manager.soap;

import sp_manager.output.*;
import sp_manager.input.*;

import java.util.concurrent.Future;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-08-25T16:25:19.449+01:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "urn:sp_manager:sp_manager:1.0", name = "ServiceName_5PortType")
@XmlSeeAlso({ ObjectFactory.class })
public interface ServiceName5PortType {

	@WebMethod(operationName = "CapabilityName_5_6")
	@Oneway
	@RequestWrapper(localName = "CapabilityName_5_6", targetNamespace = "urn:sp_manager:sp_manager:1.0", className = "sp_manager.soap.CapabilityName_5_6")
	public void capabilityName56();

	@WebMethod(operationName = "CapabilityName_5_1")
	@Oneway
	@RequestWrapper(localName = "CapabilityName_5_1", targetNamespace = "urn:sp_manager:sp_manager:1.0", className = "sp_manager.soap.CapabilityName_5_1")
	public void capabilityName51();

	@WebMethod(operationName = "CapabilityName_5_5")
	@Oneway
	@RequestWrapper(localName = "CapabilityName_5_5", targetNamespace = "urn:sp_manager:sp_manager:1.0", className = "sp_manager.soap.CapabilityName_5_5")
	public void capabilityName55(
			@WebParam(name = "arg0", targetNamespace = "urn:sp_manager:sp_manager:1.0") InputDataClassName_5_5 arg0);

	@WebMethod(operationName = "CapabilityName_5_4")
	@RequestWrapper(localName = "CapabilityName_5_4", targetNamespace = "urn:sp_manager:sp_manager:1.0", className = "sp_manager.soap.CapabilityName_5_4")
	@ResponseWrapper(localName = "CapabilityName_5_4Response", targetNamespace = "urn:sp_manager:sp_manager:1.0", className = "sp_manager.soap.CapabilityName_5_4Response")
	public Response<sp_manager.soap.CapabilityName_5_4Response> capabilityName54Async(
			@WebParam(name = "arg0", targetNamespace = "urn:sp_manager:sp_manager:1.0") InputDataClassName_5_4 arg0);

	@WebMethod(operationName = "CapabilityName_5_4")
	@ResponseWrapper(localName = "CapabilityName_5_4Response", targetNamespace = "urn:sp_manager:sp_manager:1.0", className = "sp_manager.soap.CapabilityName_5_4Response")
	@RequestWrapper(localName = "CapabilityName_5_4", targetNamespace = "urn:sp_manager:sp_manager:1.0", className = "sp_manager.soap.CapabilityName_5_4")
	public Future<?> capabilityName54Async(
			@WebParam(name = "arg0", targetNamespace = "urn:sp_manager:sp_manager:1.0") InputDataClassName_5_4 arg0,
			@WebParam(name = "asyncHandler", targetNamespace = "") AsyncHandler<sp_manager.soap.CapabilityName_5_4Response> asyncHandler);

	@WebMethod(operationName = "CapabilityName_5_4")
	@RequestWrapper(localName = "CapabilityName_5_4", targetNamespace = "urn:sp_manager:sp_manager:1.0", className = "sp_manager.soap.CapabilityName_5_4")
	@ResponseWrapper(localName = "CapabilityName_5_4Response", targetNamespace = "urn:sp_manager:sp_manager:1.0", className = "sp_manager.soap.CapabilityName_5_4Response")
	@WebResult(name = "return", targetNamespace = "")
	public OutputDataClassName_5_4 capabilityName54(
			@WebParam(name = "arg0", targetNamespace = "urn:sp_manager:sp_manager:1.0") InputDataClassName_5_4 arg0);

	@WebMethod(operationName = "CapabilityName_5_3")
	@RequestWrapper(localName = "CapabilityName_5_3", targetNamespace = "urn:sp_manager:sp_manager:1.0", className = "sp_manager.soap.CapabilityName_5_3")
	@ResponseWrapper(localName = "CapabilityName_5_3Response", targetNamespace = "urn:sp_manager:sp_manager:1.0", className = "sp_manager.soap.CapabilityName_5_3Response")
	public Response<sp_manager.soap.CapabilityName_5_3Response> capabilityName53Async(
			@WebParam(name = "arg0", targetNamespace = "urn:sp_manager:sp_manager:1.0") InputDataClassName_5_3 arg0);

	@WebMethod(operationName = "CapabilityName_5_3")
	@ResponseWrapper(localName = "CapabilityName_5_3Response", targetNamespace = "urn:sp_manager:sp_manager:1.0", className = "sp_manager.soap.CapabilityName_5_3Response")
	@RequestWrapper(localName = "CapabilityName_5_3", targetNamespace = "urn:sp_manager:sp_manager:1.0", className = "sp_manager.soap.CapabilityName_5_3")
	public Future<?> capabilityName53Async(
			@WebParam(name = "arg0", targetNamespace = "urn:sp_manager:sp_manager:1.0") InputDataClassName_5_3 arg0,
			@WebParam(name = "asyncHandler", targetNamespace = "") AsyncHandler<sp_manager.soap.CapabilityName_5_3Response> asyncHandler);

	@WebMethod(operationName = "CapabilityName_5_3")
	@RequestWrapper(localName = "CapabilityName_5_3", targetNamespace = "urn:sp_manager:sp_manager:1.0", className = "sp_manager.soap.CapabilityName_5_3")
	@ResponseWrapper(localName = "CapabilityName_5_3Response", targetNamespace = "urn:sp_manager:sp_manager:1.0", className = "sp_manager.soap.CapabilityName_5_3Response")
	@WebResult(name = "return", targetNamespace = "")
	public OutputDataClassName_5_3 capabilityName53(
			@WebParam(name = "arg0", targetNamespace = "urn:sp_manager:sp_manager:1.0") InputDataClassName_5_3 arg0);

	@WebMethod(operationName = "CapabilityName_5_2")
	@RequestWrapper(localName = "CapabilityName_5_2", targetNamespace = "urn:sp_manager:sp_manager:1.0", className = "sp_manager.soap.CapabilityName_5_2")
	@ResponseWrapper(localName = "CapabilityName_5_2Response", targetNamespace = "urn:sp_manager:sp_manager:1.0", className = "sp_manager.soap.CapabilityName_5_2Response")
	public Response<sp_manager.soap.CapabilityName_5_2Response> capabilityName52Async(
			@WebParam(name = "arg0", targetNamespace = "urn:sp_manager:sp_manager:1.0") InputDataClassName_5_2 arg0);

	@WebMethod(operationName = "CapabilityName_5_2")
	@ResponseWrapper(localName = "CapabilityName_5_2Response", targetNamespace = "urn:sp_manager:sp_manager:1.0", className = "sp_manager.soap.CapabilityName_5_2Response")
	@RequestWrapper(localName = "CapabilityName_5_2", targetNamespace = "urn:sp_manager:sp_manager:1.0", className = "sp_manager.soap.CapabilityName_5_2")
	public Future<?> capabilityName52Async(
			@WebParam(name = "arg0", targetNamespace = "urn:sp_manager:sp_manager:1.0") InputDataClassName_5_2 arg0,
			@WebParam(name = "asyncHandler", targetNamespace = "") AsyncHandler<sp_manager.soap.CapabilityName_5_2Response> asyncHandler);

	@WebMethod(operationName = "CapabilityName_5_2")
	@RequestWrapper(localName = "CapabilityName_5_2", targetNamespace = "urn:sp_manager:sp_manager:1.0", className = "sp_manager.soap.CapabilityName_5_2")
	@ResponseWrapper(localName = "CapabilityName_5_2Response", targetNamespace = "urn:sp_manager:sp_manager:1.0", className = "sp_manager.soap.CapabilityName_5_2Response")
	@WebResult(name = "return", targetNamespace = "")
	public OutputDataClassName_5_2 capabilityName52(
			@WebParam(name = "arg0", targetNamespace = "urn:sp_manager:sp_manager:1.0") InputDataClassName_5_2 arg0);
}
