package spc1.soap;

import spc1.output.*;
import spc1.input.*;

import java.util.concurrent.Future;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-09-14T19:47:20.551+01:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "urn:spc1:spc1:1.0", name = "ServiceName_3PortType")
@XmlSeeAlso({ ObjectFactory.class })
public interface ServiceName3PortType {

	@WebMethod(operationName = "CapabilityName_3_2")
	@RequestWrapper(localName = "CapabilityName_3_2", targetNamespace = "urn:spc1:spc1:1.0", className = "spc1.soap.CapabilityName_3_2")
	@ResponseWrapper(localName = "CapabilityName_3_2Response", targetNamespace = "urn:spc1:spc1:1.0", className = "spc1.soap.CapabilityName_3_2Response")
	public Response<spc1.soap.CapabilityName_3_2Response> capabilityName32Async(
			@WebParam(name = "arg0", targetNamespace = "urn:spc1:spc1:1.0") InputDataClassName_3_2 arg0);

	@WebMethod(operationName = "CapabilityName_3_2")
	@ResponseWrapper(localName = "CapabilityName_3_2Response", targetNamespace = "urn:spc1:spc1:1.0", className = "spc1.soap.CapabilityName_3_2Response")
	@RequestWrapper(localName = "CapabilityName_3_2", targetNamespace = "urn:spc1:spc1:1.0", className = "spc1.soap.CapabilityName_3_2")
	public Future<?> capabilityName32Async(
			@WebParam(name = "arg0", targetNamespace = "urn:spc1:spc1:1.0") InputDataClassName_3_2 arg0,
			@WebParam(name = "asyncHandler", targetNamespace = "") AsyncHandler<spc1.soap.CapabilityName_3_2Response> asyncHandler);

	@WebMethod(operationName = "CapabilityName_3_2")
	@RequestWrapper(localName = "CapabilityName_3_2", targetNamespace = "urn:spc1:spc1:1.0", className = "spc1.soap.CapabilityName_3_2")
	@ResponseWrapper(localName = "CapabilityName_3_2Response", targetNamespace = "urn:spc1:spc1:1.0", className = "spc1.soap.CapabilityName_3_2Response")
	@WebResult(name = "return", targetNamespace = "")
	public OutputDataClassName_3_2 capabilityName32(
			@WebParam(name = "arg0", targetNamespace = "urn:spc1:spc1:1.0") InputDataClassName_3_2 arg0);

	@WebMethod(operationName = "CapabilityName_3_1")
	@Oneway
	@RequestWrapper(localName = "CapabilityName_3_1", targetNamespace = "urn:spc1:spc1:1.0", className = "spc1.soap.CapabilityName_3_1")
	public void capabilityName31();
}
