package a1.soap;

import a1.output.*;
import a1.input.*;

import java.util.concurrent.Future;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-08-25T23:11:11.642+01:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "urn:a1:a1:1.0", name = "ServiceName_1PortType")
@XmlSeeAlso({ ObjectFactory.class })
public interface ServiceName1PortType {

	@WebMethod(operationName = "CapabilityName_1_1")
	@Oneway
	@RequestWrapper(localName = "CapabilityName_1_1", targetNamespace = "urn:a1:a1:1.0", className = "a1.soap.CapabilityName_1_1")
	public void capabilityName11(
			@WebParam(name = "arg0", targetNamespace = "urn:a1:a1:1.0") InputDataClassName_1_1 arg0);

	@WebMethod(operationName = "CapabilityName_1_2")
	@RequestWrapper(localName = "CapabilityName_1_2", targetNamespace = "urn:a1:a1:1.0", className = "a1.soap.CapabilityName_1_2")
	@ResponseWrapper(localName = "CapabilityName_1_2Response", targetNamespace = "urn:a1:a1:1.0", className = "a1.soap.CapabilityName_1_2Response")
	public Response<a1.soap.CapabilityName_1_2Response> capabilityName12Async();

	@WebMethod(operationName = "CapabilityName_1_2")
	@ResponseWrapper(localName = "CapabilityName_1_2Response", targetNamespace = "urn:a1:a1:1.0", className = "a1.soap.CapabilityName_1_2Response")
	@RequestWrapper(localName = "CapabilityName_1_2", targetNamespace = "urn:a1:a1:1.0", className = "a1.soap.CapabilityName_1_2")
	public Future<?> capabilityName12Async(
			@WebParam(name = "asyncHandler", targetNamespace = "") AsyncHandler<a1.soap.CapabilityName_1_2Response> asyncHandler);

	@WebMethod(operationName = "CapabilityName_1_2")
	@RequestWrapper(localName = "CapabilityName_1_2", targetNamespace = "urn:a1:a1:1.0", className = "a1.soap.CapabilityName_1_2")
	@ResponseWrapper(localName = "CapabilityName_1_2Response", targetNamespace = "urn:a1:a1:1.0", className = "a1.soap.CapabilityName_1_2Response")
	@WebResult(name = "return", targetNamespace = "")
	public OutputDataClassName_1_2 capabilityName12();
}
