package SP_helicopter1.soap;

import SP_helicopter1.output.*;
import SP_helicopter1.input.*;

import java.util.concurrent.Future;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-06-11T03:12:04.539+01:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0", name = "ServiceName_5PortType")
@XmlSeeAlso({ ObjectFactory.class })
public interface ServiceName5PortType {

	@WebMethod(operationName = "CapabilityName_5_4")
	@RequestWrapper(localName = "CapabilityName_5_4", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0", className = "SP_helicopter1.soap.CapabilityName_5_4")
	@ResponseWrapper(localName = "CapabilityName_5_4Response", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0", className = "SP_helicopter1.soap.CapabilityName_5_4Response")
	public Response<SP_helicopter1.soap.CapabilityName_5_4Response> capabilityName54Async(
			@WebParam(name = "arg0", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0") InputDataClassName_5_4 arg0);

	@WebMethod(operationName = "CapabilityName_5_4")
	@ResponseWrapper(localName = "CapabilityName_5_4Response", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0", className = "SP_helicopter1.soap.CapabilityName_5_4Response")
	@RequestWrapper(localName = "CapabilityName_5_4", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0", className = "SP_helicopter1.soap.CapabilityName_5_4")
	public Future<?> capabilityName54Async(
			@WebParam(name = "arg0", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0") InputDataClassName_5_4 arg0,
			@WebParam(name = "asyncHandler", targetNamespace = "") AsyncHandler<SP_helicopter1.soap.CapabilityName_5_4Response> asyncHandler);

	@WebMethod(operationName = "CapabilityName_5_4")
	@RequestWrapper(localName = "CapabilityName_5_4", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0", className = "SP_helicopter1.soap.CapabilityName_5_4")
	@ResponseWrapper(localName = "CapabilityName_5_4Response", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0", className = "SP_helicopter1.soap.CapabilityName_5_4Response")
	@WebResult(name = "return", targetNamespace = "")
	public OutputDataClassName_5_4 capabilityName54(
			@WebParam(name = "arg0", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0") InputDataClassName_5_4 arg0);

	@WebMethod(operationName = "CapabilityName_5_2")
	@Oneway
	@RequestWrapper(localName = "CapabilityName_5_2", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0", className = "SP_helicopter1.soap.CapabilityName_5_2")
	public void capabilityName52(
			@WebParam(name = "arg0", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0") InputDataClassName_5_2 arg0);

	@WebMethod(operationName = "CapabilityName_5_3")
	@RequestWrapper(localName = "CapabilityName_5_3", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0", className = "SP_helicopter1.soap.CapabilityName_5_3")
	@ResponseWrapper(localName = "CapabilityName_5_3Response", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0", className = "SP_helicopter1.soap.CapabilityName_5_3Response")
	public Response<SP_helicopter1.soap.CapabilityName_5_3Response> capabilityName53Async(
			@WebParam(name = "arg0", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0") InputDataClassName_5_3 arg0);

	@WebMethod(operationName = "CapabilityName_5_3")
	@ResponseWrapper(localName = "CapabilityName_5_3Response", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0", className = "SP_helicopter1.soap.CapabilityName_5_3Response")
	@RequestWrapper(localName = "CapabilityName_5_3", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0", className = "SP_helicopter1.soap.CapabilityName_5_3")
	public Future<?> capabilityName53Async(
			@WebParam(name = "arg0", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0") InputDataClassName_5_3 arg0,
			@WebParam(name = "asyncHandler", targetNamespace = "") AsyncHandler<SP_helicopter1.soap.CapabilityName_5_3Response> asyncHandler);

	@WebMethod(operationName = "CapabilityName_5_3")
	@RequestWrapper(localName = "CapabilityName_5_3", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0", className = "SP_helicopter1.soap.CapabilityName_5_3")
	@ResponseWrapper(localName = "CapabilityName_5_3Response", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0", className = "SP_helicopter1.soap.CapabilityName_5_3Response")
	@WebResult(name = "return", targetNamespace = "")
	public OutputDataClassName_5_3 capabilityName53(
			@WebParam(name = "arg0", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0") InputDataClassName_5_3 arg0);

	@WebMethod(operationName = "CapabilityName_5_1")
	@RequestWrapper(localName = "CapabilityName_5_1", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0", className = "SP_helicopter1.soap.CapabilityName_5_1")
	@ResponseWrapper(localName = "CapabilityName_5_1Response", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0", className = "SP_helicopter1.soap.CapabilityName_5_1Response")
	public Response<SP_helicopter1.soap.CapabilityName_5_1Response> capabilityName51Async(
			@WebParam(name = "arg0", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0") InputDataClassName_5_1 arg0);

	@WebMethod(operationName = "CapabilityName_5_1")
	@ResponseWrapper(localName = "CapabilityName_5_1Response", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0", className = "SP_helicopter1.soap.CapabilityName_5_1Response")
	@RequestWrapper(localName = "CapabilityName_5_1", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0", className = "SP_helicopter1.soap.CapabilityName_5_1")
	public Future<?> capabilityName51Async(
			@WebParam(name = "arg0", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0") InputDataClassName_5_1 arg0,
			@WebParam(name = "asyncHandler", targetNamespace = "") AsyncHandler<SP_helicopter1.soap.CapabilityName_5_1Response> asyncHandler);

	@WebMethod(operationName = "CapabilityName_5_1")
	@RequestWrapper(localName = "CapabilityName_5_1", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0", className = "SP_helicopter1.soap.CapabilityName_5_1")
	@ResponseWrapper(localName = "CapabilityName_5_1Response", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0", className = "SP_helicopter1.soap.CapabilityName_5_1Response")
	@WebResult(name = "return", targetNamespace = "")
	public OutputDataClassName_5_1 capabilityName51(
			@WebParam(name = "arg0", targetNamespace = "urn:SP_helicopter1:SP_helicopter1:1.0") InputDataClassName_5_1 arg0);
}
