package large3.soap;

import large3.output.*;
import large3.input.*;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-09-15T23:31:47.737+01:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "urn:large3:large3:1.0", name = "ServiceName_6PortType")
@XmlSeeAlso({ ObjectFactory.class })
public interface ServiceName6PortType {

	@WebMethod(operationName = "CapabilityName_6_4")
	@RequestWrapper(localName = "CapabilityName_6_4", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_4")
	@ResponseWrapper(localName = "CapabilityName_6_4Response", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_4Response")
	public Response<large3.soap.CapabilityName_6_4Response> capabilityName64Async(
			@WebParam(name = "arg0", targetNamespace = "urn:large3:large3:1.0") InputDataClassName_6_4 arg0);

	@WebMethod(operationName = "CapabilityName_6_4")
	@ResponseWrapper(localName = "CapabilityName_6_4Response", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_4Response")
	@RequestWrapper(localName = "CapabilityName_6_4", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_4")
	public Future<?> capabilityName64Async(
			@WebParam(name = "arg0", targetNamespace = "urn:large3:large3:1.0") InputDataClassName_6_4 arg0,
			@WebParam(name = "asyncHandler", targetNamespace = "") AsyncHandler<large3.soap.CapabilityName_6_4Response> asyncHandler);

	@WebMethod(operationName = "CapabilityName_6_4")
	@RequestWrapper(localName = "CapabilityName_6_4", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_4")
	@ResponseWrapper(localName = "CapabilityName_6_4Response", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_4Response")
	@WebResult(name = "return", targetNamespace = "")
	public OutputDataClassName_6_4 capabilityName64(
			@WebParam(name = "arg0", targetNamespace = "urn:large3:large3:1.0") InputDataClassName_6_4 arg0);

	@WebMethod(operationName = "CapabilityName_6_3")
	@RequestWrapper(localName = "CapabilityName_6_3", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_3")
	@ResponseWrapper(localName = "CapabilityName_6_3Response", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_3Response")
	public Response<large3.soap.CapabilityName_6_3Response> capabilityName63Async(
			@WebParam(name = "arg0", targetNamespace = "urn:large3:large3:1.0") InputDataClassName_6_3 arg0);

	@WebMethod(operationName = "CapabilityName_6_3")
	@ResponseWrapper(localName = "CapabilityName_6_3Response", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_3Response")
	@RequestWrapper(localName = "CapabilityName_6_3", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_3")
	public Future<?> capabilityName63Async(
			@WebParam(name = "arg0", targetNamespace = "urn:large3:large3:1.0") InputDataClassName_6_3 arg0,
			@WebParam(name = "asyncHandler", targetNamespace = "") AsyncHandler<large3.soap.CapabilityName_6_3Response> asyncHandler);

	@WebMethod(operationName = "CapabilityName_6_3")
	@RequestWrapper(localName = "CapabilityName_6_3", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_3")
	@ResponseWrapper(localName = "CapabilityName_6_3Response", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_3Response")
	@WebResult(name = "return", targetNamespace = "")
	public OutputDataClassName_6_3 capabilityName63(
			@WebParam(name = "arg0", targetNamespace = "urn:large3:large3:1.0") InputDataClassName_6_3 arg0);

	@WebMethod(operationName = "CapabilityName_6_2")
	@RequestWrapper(localName = "CapabilityName_6_2", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_2")
	@ResponseWrapper(localName = "CapabilityName_6_2Response", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_2Response")
	public Response<large3.soap.CapabilityName_6_2Response> capabilityName62Async(
			@WebParam(name = "arg0", targetNamespace = "urn:large3:large3:1.0") InputDataClassName_6_2 arg0);

	@WebMethod(operationName = "CapabilityName_6_2")
	@ResponseWrapper(localName = "CapabilityName_6_2Response", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_2Response")
	@RequestWrapper(localName = "CapabilityName_6_2", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_2")
	public Future<?> capabilityName62Async(
			@WebParam(name = "arg0", targetNamespace = "urn:large3:large3:1.0") InputDataClassName_6_2 arg0,
			@WebParam(name = "asyncHandler", targetNamespace = "") AsyncHandler<large3.soap.CapabilityName_6_2Response> asyncHandler);

	@WebMethod(operationName = "CapabilityName_6_2")
	@RequestWrapper(localName = "CapabilityName_6_2", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_2")
	@ResponseWrapper(localName = "CapabilityName_6_2Response", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_2Response")
	@WebResult(name = "return", targetNamespace = "")
	public OutputDataClassName_6_2 capabilityName62(
			@WebParam(name = "arg0", targetNamespace = "urn:large3:large3:1.0") InputDataClassName_6_2 arg0);

	@WebMethod(operationName = "CapabilityName_6_1")
	@RequestWrapper(localName = "CapabilityName_6_1", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_1")
	@ResponseWrapper(localName = "CapabilityName_6_1Response", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_1Response")
	public Response<large3.soap.CapabilityName_6_1Response> capabilityName61Async(
			@WebParam(name = "arg0", targetNamespace = "urn:large3:large3:1.0") InputDataClassName_6_1 arg0);

	@WebMethod(operationName = "CapabilityName_6_1")
	@ResponseWrapper(localName = "CapabilityName_6_1Response", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_1Response")
	@RequestWrapper(localName = "CapabilityName_6_1", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_1")
	public Future<?> capabilityName61Async(
			@WebParam(name = "arg0", targetNamespace = "urn:large3:large3:1.0") InputDataClassName_6_1 arg0,
			@WebParam(name = "asyncHandler", targetNamespace = "") AsyncHandler<large3.soap.CapabilityName_6_1Response> asyncHandler);

	@WebMethod(operationName = "CapabilityName_6_1")
	@RequestWrapper(localName = "CapabilityName_6_1", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_1")
	@ResponseWrapper(localName = "CapabilityName_6_1Response", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_1Response")
	@WebResult(name = "return", targetNamespace = "")
	public OutputDataClassName_6_1 capabilityName61(
			@WebParam(name = "arg0", targetNamespace = "urn:large3:large3:1.0") InputDataClassName_6_1 arg0);

	@WebMethod(operationName = "CapabilityName_6_6")
	@RequestWrapper(localName = "CapabilityName_6_6", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_6")
	@ResponseWrapper(localName = "CapabilityName_6_6Response", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_6Response")
	public Response<large3.soap.CapabilityName_6_6Response> capabilityName66Async(
			@WebParam(name = "arg0", targetNamespace = "urn:large3:large3:1.0") InputDataClassName_6_6 arg0);

	@WebMethod(operationName = "CapabilityName_6_6")
	@ResponseWrapper(localName = "CapabilityName_6_6Response", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_6Response")
	@RequestWrapper(localName = "CapabilityName_6_6", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_6")
	public Future<?> capabilityName66Async(
			@WebParam(name = "arg0", targetNamespace = "urn:large3:large3:1.0") InputDataClassName_6_6 arg0,
			@WebParam(name = "asyncHandler", targetNamespace = "") AsyncHandler<large3.soap.CapabilityName_6_6Response> asyncHandler);

	@WebMethod(operationName = "CapabilityName_6_6")
	@RequestWrapper(localName = "CapabilityName_6_6", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_6")
	@ResponseWrapper(localName = "CapabilityName_6_6Response", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_6Response")
	@WebResult(name = "return", targetNamespace = "")
	public OutputDataClassName_6_6 capabilityName66(
			@WebParam(name = "arg0", targetNamespace = "urn:large3:large3:1.0") InputDataClassName_6_6 arg0);

	@WebMethod(operationName = "CapabilityName_6_5")
	@RequestWrapper(localName = "CapabilityName_6_5", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_5")
	@ResponseWrapper(localName = "CapabilityName_6_5Response", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_5Response")
	public Response<large3.soap.CapabilityName_6_5Response> capabilityName65Async(
			@WebParam(name = "arg0", targetNamespace = "urn:large3:large3:1.0") InputDataClassName_6_5 arg0);

	@WebMethod(operationName = "CapabilityName_6_5")
	@ResponseWrapper(localName = "CapabilityName_6_5Response", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_5Response")
	@RequestWrapper(localName = "CapabilityName_6_5", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_5")
	public Future<?> capabilityName65Async(
			@WebParam(name = "arg0", targetNamespace = "urn:large3:large3:1.0") InputDataClassName_6_5 arg0,
			@WebParam(name = "asyncHandler", targetNamespace = "") AsyncHandler<large3.soap.CapabilityName_6_5Response> asyncHandler);

	@WebMethod(operationName = "CapabilityName_6_5")
	@RequestWrapper(localName = "CapabilityName_6_5", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_5")
	@ResponseWrapper(localName = "CapabilityName_6_5Response", targetNamespace = "urn:large3:large3:1.0", className = "large3.soap.CapabilityName_6_5Response")
	@WebResult(name = "return", targetNamespace = "")
	public OutputDataClassName_6_5 capabilityName65(
			@WebParam(name = "arg0", targetNamespace = "urn:large3:large3:1.0") InputDataClassName_6_5 arg0);
}
