package SP_aircraftcarrier1.soap;

import SP_aircraftcarrier1.output.*;
import SP_aircraftcarrier1.input.*;

import java.util.concurrent.Future;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-03-24T20:46:01.186+01:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "urn:SP_aircraftcarrier1:SP_aircraftcarrier1:1.0", name = "ServiceName_2PortType")
@XmlSeeAlso({ ObjectFactory.class })
public interface ServiceName2PortType {

	@WebMethod(operationName = "CapabilityName_2_3")
	@RequestWrapper(localName = "CapabilityName_2_3", targetNamespace = "urn:SP_aircraftcarrier1:SP_aircraftcarrier1:1.0", className = "SP_aircraftcarrier1.soap.CapabilityName_2_3")
	@ResponseWrapper(localName = "CapabilityName_2_3Response", targetNamespace = "urn:SP_aircraftcarrier1:SP_aircraftcarrier1:1.0", className = "SP_aircraftcarrier1.soap.CapabilityName_2_3Response")
	public Response<SP_aircraftcarrier1.soap.CapabilityName_2_3Response> capabilityName23Async(
			@WebParam(name = "arg0", targetNamespace = "urn:SP_aircraftcarrier1:SP_aircraftcarrier1:1.0") InputDataClassName_2_3 arg0);

	@WebMethod(operationName = "CapabilityName_2_3")
	@ResponseWrapper(localName = "CapabilityName_2_3Response", targetNamespace = "urn:SP_aircraftcarrier1:SP_aircraftcarrier1:1.0", className = "SP_aircraftcarrier1.soap.CapabilityName_2_3Response")
	@RequestWrapper(localName = "CapabilityName_2_3", targetNamespace = "urn:SP_aircraftcarrier1:SP_aircraftcarrier1:1.0", className = "SP_aircraftcarrier1.soap.CapabilityName_2_3")
	public Future<?> capabilityName23Async(
			@WebParam(name = "arg0", targetNamespace = "urn:SP_aircraftcarrier1:SP_aircraftcarrier1:1.0") InputDataClassName_2_3 arg0,
			@WebParam(name = "asyncHandler", targetNamespace = "") AsyncHandler<SP_aircraftcarrier1.soap.CapabilityName_2_3Response> asyncHandler);

	@WebMethod(operationName = "CapabilityName_2_3")
	@RequestWrapper(localName = "CapabilityName_2_3", targetNamespace = "urn:SP_aircraftcarrier1:SP_aircraftcarrier1:1.0", className = "SP_aircraftcarrier1.soap.CapabilityName_2_3")
	@ResponseWrapper(localName = "CapabilityName_2_3Response", targetNamespace = "urn:SP_aircraftcarrier1:SP_aircraftcarrier1:1.0", className = "SP_aircraftcarrier1.soap.CapabilityName_2_3Response")
	@WebResult(name = "return", targetNamespace = "")
	public OutputDataClassName_2_3 capabilityName23(
			@WebParam(name = "arg0", targetNamespace = "urn:SP_aircraftcarrier1:SP_aircraftcarrier1:1.0") InputDataClassName_2_3 arg0);

	@WebMethod(operationName = "CapabilityName_2_2")
	@RequestWrapper(localName = "CapabilityName_2_2", targetNamespace = "urn:SP_aircraftcarrier1:SP_aircraftcarrier1:1.0", className = "SP_aircraftcarrier1.soap.CapabilityName_2_2")
	@ResponseWrapper(localName = "CapabilityName_2_2Response", targetNamespace = "urn:SP_aircraftcarrier1:SP_aircraftcarrier1:1.0", className = "SP_aircraftcarrier1.soap.CapabilityName_2_2Response")
	public Response<SP_aircraftcarrier1.soap.CapabilityName_2_2Response> capabilityName22Async();

	@WebMethod(operationName = "CapabilityName_2_2")
	@ResponseWrapper(localName = "CapabilityName_2_2Response", targetNamespace = "urn:SP_aircraftcarrier1:SP_aircraftcarrier1:1.0", className = "SP_aircraftcarrier1.soap.CapabilityName_2_2Response")
	@RequestWrapper(localName = "CapabilityName_2_2", targetNamespace = "urn:SP_aircraftcarrier1:SP_aircraftcarrier1:1.0", className = "SP_aircraftcarrier1.soap.CapabilityName_2_2")
	public Future<?> capabilityName22Async(
			@WebParam(name = "asyncHandler", targetNamespace = "") AsyncHandler<SP_aircraftcarrier1.soap.CapabilityName_2_2Response> asyncHandler);

	@WebMethod(operationName = "CapabilityName_2_2")
	@RequestWrapper(localName = "CapabilityName_2_2", targetNamespace = "urn:SP_aircraftcarrier1:SP_aircraftcarrier1:1.0", className = "SP_aircraftcarrier1.soap.CapabilityName_2_2")
	@ResponseWrapper(localName = "CapabilityName_2_2Response", targetNamespace = "urn:SP_aircraftcarrier1:SP_aircraftcarrier1:1.0", className = "SP_aircraftcarrier1.soap.CapabilityName_2_2Response")
	@WebResult(name = "return", targetNamespace = "")
	public OutputDataClassName_2_2 capabilityName22();

	@WebMethod(operationName = "CapabilityName_2_1")
	@Oneway
	@RequestWrapper(localName = "CapabilityName_2_1", targetNamespace = "urn:SP_aircraftcarrier1:SP_aircraftcarrier1:1.0", className = "SP_aircraftcarrier1.soap.CapabilityName_2_1")
	public void capabilityName21(
			@WebParam(name = "arg0", targetNamespace = "urn:SP_aircraftcarrier1:SP_aircraftcarrier1:1.0") InputDataClassName_2_1 arg0);
}
