<?xml version="1.0" encoding="UTF-8" standalone="no"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="urn:gen1:gen1:1.0" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="urn:gen1:gen1:1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ServiceName_2" targetNamespace="urn:gen1:gen1:1.0">
  <wsdl:types>
<xsd:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="urn:gen1:gen1:1.0">
  <xsd:element name="CapabilityName_2_2" type="tns:CapabilityName_2_2"/>
  <xsd:complexType name="CapabilityName_2_2">
    <xsd:sequence/>
  </xsd:complexType>
  
  
  <xsd:element name="CapabilityName_2_1" type="tns:CapabilityName_2_1"/>
  <xsd:complexType name="CapabilityName_2_1">
    <xsd:sequence/>
  </xsd:complexType>
  
  
</xsd:schema>
  </wsdl:types>
  
  
  <wsdl:message name="CapabilityName_2_2">
    <wsdl:part element="ns1:CapabilityName_2_2" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="CapabilityName_2_1">
    <wsdl:part element="ns1:CapabilityName_2_1" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="ServiceName_2PortType">
    <wsdl:operation name="CapabilityName_2_2">
      <wsdl:input message="ns1:CapabilityName_2_2" name="CapabilityName_2_2">
    </wsdl:input>
      
    </wsdl:operation>
    <wsdl:operation name="CapabilityName_2_1">
      <wsdl:input message="ns1:CapabilityName_2_1" name="CapabilityName_2_1">
    </wsdl:input>
      
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ServiceName_2SoapBinding" type="ns1:ServiceName_2PortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="CapabilityName_2_2">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="CapabilityName_2_2">
        <soap:body use="literal"/>
      </wsdl:input>
      
    </wsdl:operation>
    <wsdl:operation name="CapabilityName_2_1">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="CapabilityName_2_1">
        <soap:body use="literal"/>
      </wsdl:input>
      
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ServiceName_2">
    <wsdl:port binding="ns1:ServiceName_2SoapBinding" name="ServiceName_2Port">
      <soap:address location="http://localhost:8080/ServiceName_2/ServiceName_2"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>